export const theme = {
  colors: {
    // ToBump CGP v2 — sand + deep teal
    primary: '#1F6B73',
    primaryDark: '#154F55',
    primarySoft: '#D3E0DE',
    primaryMuted: '#B7CBC9',
    accent: '#C96A4A',
    background: '#E4DCCE',
    surface: '#EFE8DB',
    surfaceElevated: '#F6F0E4',
    text: '#1A1F1E',
    textMuted: '#6B6560',
    border: '#D4CBBA',
    borderStrong: '#C4B8A4',
    danger: '#C0392B',
    dangerSoft: '#F3E4DE',
    success: '#3E8A68',
    warning: '#C47A1A',
    warningSoft: '#F0E4C8',
    infoSoft: '#D3E0DE',
    info: '#154F55',
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 18,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  shadow: {
    card: {
      shadowColor: '#154F55',
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
  },
} as const;
