export const theme = {
  colors: {
    // ToBump CGP v3 — Igrišče: organizacija (trava) + gibanje (terakota)
    primary: '#4A7A52',
    primaryDark: '#355A3C',
    primarySoft: '#DCE6DC',
    primaryMuted: '#B7C9B8',
    accent: '#C45C38',
    background: '#E5E8E1',
    surface: '#F3F5F0',
    surfaceElevated: '#F7F8F5',
    text: '#1A1F1E',
    textMuted: '#5F6861',
    border: '#D0D6CC',
    borderStrong: '#B8C2B6',
    danger: '#C0392B',
    dangerSoft: '#F3E4DE',
    success: '#3E8A68',
    warning: '#C47A1A',
    warningSoft: '#F0E4C8',
    infoSoft: '#DCE6DC',
    info: '#355A3C',
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 18,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  shadow: {
    card: {
      shadowColor: '#355A3C',
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
  },
} as const;
