export const theme = {
  colors: {
    primary: '#0B6E4F',
    primaryDark: '#084C37',
    primarySoft: '#E6F4EF',
    primaryMuted: '#C5E4D7',
    accent: '#E8913A',
    background: '#F3F6F4',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    text: '#14201B',
    textMuted: '#5F6F68',
    border: '#D7E0DB',
    borderStrong: '#B7C7BF',
    danger: '#C0392B',
    dangerSoft: '#FCE8E6',
    success: '#1B7F5A',
    warning: '#D97706',
    warningSoft: '#FEF3C7',
    infoSoft: '#E0F2FE',
    info: '#0369A1',
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 18,
  },
  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  shadow: {
    card: {
      shadowColor: '#0B6E4F',
      shadowOpacity: 0.08,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
  },
} as const;
